-- 1. Affichez les sociétés, adresse et villes de résidence pour tous les tiers de l’entreprise.
---     Trier par société
SELECT SOCIETE,
	ADRESSE,
	VILLE
FROM CLIENTS
UNION
SELECT SOCIETE,
	ADRESSE,
	VILLE
FROM FOURNISSEURS
ORDER BY SOCIETE;
-- 2. Affichez toutes les commandes qui comportent en même temps des produits de catégorie 1 du
---     fournisseur 1 et des produits de catégorie 2 du fournisseur 2.
--- Toutes bases de données :
SELECT NO_COMMANDE
FROM DETAILS_COMMANDES dc
	JOIN PRODUITS p ON dc.REF_PRODUIT = p.REF_PRODUIT
WHERE CODE_CATEGORIE = 1
	AND NO_FOURNISSEUR = 1
	AND no_commande NOT IN (
		SELECT NO_COMMANDE
		FROM DETAILS_COMMANDES dc
			JOIN PRODUITS p ON dc.REF_PRODUIT = p.REF_PRODUIT
		WHERE CODE_CATEGORIE = 2
			AND NO_FOURNISSEUR = 2
	);
--- ORACLE, SQL SERVER et POSTGRESQL
SELECT NO_COMMANDE
FROM DETAILS_COMMANDES dc
	JOIN PRODUITS p ON dc.REF_PRODUIT = p.REF_PRODUIT
WHERE CODE_CATEGORIE = 1
	AND NO_FOURNISSEUR = 1
INTERSECT
SELECT NO_COMMANDE
FROM DETAILS_COMMANDES dc
	JOIN PRODUITS p ON dc.REF_PRODUIT = p.REF_PRODUIT
WHERE CODE_CATEGORIE = 2
	AND NO_FOURNISSEUR = 2;
--- 3. Affichez la liste des produits que les clients parisiens ne commandent pas.
--- Toutes bases de données
SELECT REF_PRODUIT
FROM PRODUITS
WHERE REF_PRODUIT NOT IN (
		SELECT REF_PRODUIT
		FROM DETAILS_COMMANDES dc
			JOIN COMMANDES cmd ON dc.NO_COMMANDE = cmd.NO_COMMANDE
			JOIN CLIENTS cl ON cmd.CODE_CLIENT = cl.CODE_CLIENT
		WHERE VILLE = "Paris"
	);
--- ORACLE
SELECT REF_PRODUIT
FROM PRODUITS
MINUS
SELECT REF_PRODUIT
FROM DETAILS_COMMANDES dc
	JOIN COMMANDES cmd ON dc.NO_COMMANDE = cmd.NO_COMMANDE
	JOIN CLIENTS cl ON cmd.CODE_CLIENT = cl.CODE_CLIENT
WHERE VILLE = 'paris';
--- SQL SERVER et POSTGRESQL
SELECT REF_PRODUIT
FROM PRODUITS
EXCEPT
SELECT REF_PRODUIT
FROM DETAILS_COMMANDES dc
	JOIN COMMANDES cmd ON dc.NO_COMMANDE = cmd.NO_COMMANDE
	JOIN CLIENTS cl ON cmd.CODE_CLIENT = cl.CODE_CLIENT
WHERE VILLE = 'paris';